Add copier sequence diagram
VOLTTRON/copier-poetry-volttron-agent pull request #17
Opened 2022-04-04 20:56 UTC by bonicim

2022-04-05 22:50 UTC, kefeimo commented
The following figure from [Copier's readthedocs](https://copier.readthedocs.io/en/stable/) indicates the workflow.
![image](https://user-images.githubusercontent.com/28743873/161863559-70c62885-dcfb-464c-9136-d25fb201237a.png)

Note the term: template, project.

2022-04-05 22:51 UTC, kefeimo requested changes

2022-04-05 22:51 UTC, kefeimo commented on copier_workflow.txt
> +User->svn: Push agent files to remote repo
Consider integrating Craig's comment in https://github.com/VOLTTRON/copier-poetry-volttron-agent/issues/9#issuecomment-1076901232

User->Copier: Start Copier agent wizard ("Runs copier command")

2022-04-05 22:51 UTC, kefeimo commented on copier_workflow.txt
> +User->Copier: Start Copier agent wizard (similar to vcfg experience)
I am not sure how much is "vcfg experience" relevant here.

2022-04-05 22:51 UTC, kefeimo commented on copier_workflow.txt
> +Copier->Agent files: Create agent directory and source files
Is "Agent files" meaning "Copier agent template" (i.e., with jinja), or "Copier-generated files".

Discussion: unify the terminology. I have been using the terms: "Copier source code" (i.e., from which pip install copier), "Copier template"/"Agent template" (i.e., the one we are working on), "Copier generated files"/"Agent artifacts".

2022-04-05 22:51 UTC, kefeimo commented on copier_workflow.txt
> +Copier->Agent files: Create agent directory and source files
The following figure from [Copier's readthedocs](https://copier.readthedocs.io/en/stable/) indicates the workflow.
![image](https://user-images.githubusercontent.com/28743873/161863559-70c62885-dcfb-464c-9136-d25fb201237a.png)

Note the term: template, project.

2022-04-08 23:52 UTC, bonicim commented on copier_workflow.txt
> +User->Copier: Start Copier agent wizard (similar to vcfg experience)
Relevant in the sense that 'vcfg' asks you several questions to help setup your Volttron platform. The copier tool also asks you several questions to help setup your Agent source code.

2022-04-08 23:53 UTC, bonicim commented on copier_workflow.txt
> +User->svn: Push agent files to remote repo
Will do.

2022-04-08 23:58 UTC, bonicim commented on copier_workflow.txt
> +Copier->Agent files: Create agent directory and source files
Agent files means "Copier-generated files".

I don't understand what you mean by unifying the terminology. We should talk over the phone about what you mean.

2022-04-18 21:13 UTC, merged