8 make readme more clear and user friendly
VOLTTRON/copier-poetry-volttron-agent pull request #41
Opened 2022-04-22 19:14 UTC by bonicim

Fixes #8

2022-04-22 21:01 UTC, kefeimo requested changes

2022-04-22 21:01 UTC, kefeimo commented on README.md
>  starting point the agent templates would not be what they are today!
The copy-and-paste is incomplete.

Many thanks to the project [copier poetry](https://github.com/pawamoy/copier-poetry)
for starting this project and allowing the reuse of the codebase.  Without this
starting point the agent templates would not be what they are today!

2022-04-22 21:22 UTC, schandrika commented
After the workflow diagram, could you put in the steps in words. 
ie. 
1. Modify agent code
2. git init
3. git commit (mention this run the pre commit check)
4. fix issue
5. Add remote
6. git push
7. When they are ready how to push to pypi ?

2022-04-22 21:38 UTC, bonicim commented on README.md
>  starting point the agent templates would not be what they are today!
I don't understand. What part is incomplete? Can you elaborate please?

2022-04-22 21:38 UTC, bonicim commented
> After the workflow diagram, could you put in the steps in words. ie.
> 
> 1. Modify agent code
> 2. git init
> 3. git commit (mention this run the pre commit check)
> 4. fix issue
> 5. Add remote
> 6. git push
> 7. When they are ready how to push to pypi ?

Will do.

2022-04-23 00:22 UTC, kefeimo commented on README.md
>  starting point the agent templates would not be what they are today!
I missed the part that is folded. My bad. Nothing wrong here.

2022-04-23 03:12 UTC, kefeimo approved these changes

2022-04-25 16:14 UTC, merged